#!/usr/bin/bash
# vim:set ts=3:

shopt -s lastpipe

if ! mountpoint -q "${ESP_ROOT}"; then
	echo "${ESP_ROOT} is not a mountpoint, aborting..." 1>&2
	exit 1
fi

if ! [[ -d ${ESP_ROOT}/loader ]]; then
	echo "directory ${ESP_ROOT}/loader not found, aborting..." 1>&2
	exit 1
fi

if ! read MACHINE_ID < /etc/machine-id; then
	echo "file /etc/machine-id is empty, aborting..." 1>&2
	exit 1
fi

if ! ls -v -r /lib/modules | read LASTKRN; then
	echo "failed to determine latest kernel version, aborting ..." 1>&2
	exit 1
fi

if ! [[ -e ${ESP_ROOT}/$MACHINE_ID/$LASTKRN ]]; then
	echo "$MACHINE_ID/$LASTKRN not found under ${ESP_ROOT}, aborting..." 1>&2
	exit 1
fi

findmnt -n -l --output source "${ESP_ROOT}" | read SRC
findmnt -n -l --output target "$SRC" | grep "^${ESP_ROOT}@[a-z]$" | read TGT
if [[ -z $TGT ]]; then
	echo "${ESP_ROOT} does not appear to be a bind mount of ${ESP_ROOT}@[a-z], aborting..." 1>&2
	exit 1
fi

if [[ -t 1 ]]; then
	VERBOSITY='-v'
else
	VERBOSITY='-q'
fi

RETURN=0
for m in ${ESP_ROOT}@[a-z]; do
	mountpoint -q "$m" || continue
	[[ $m == $TGT ]] && continue

	if [[ -d $m/$MACHINE_ID ]]; then
		ls -v -r "$m/$MACHINE_ID" | read LASTESP
		printf "$LASTKRN\n$LASTESP\n" | sort -V -r | read GREATER
		if [[ $GREATER != $LASTKRN ]]; then
			echo "newer kernel detected on $m, refusing to update..." 1>&2
			continue
		fi
	fi

	rsync "$VERBOSITY" -r --delete --include="*/" --include="**$MACHINE_ID**" --exclude="*" "${ESP_ROOT}/" "$m"
	RETURN=$(($RETURN || $?))
done

exit $RETURN
