#!/usr/bin/bash
# vim:set ts=3:

shopt -s dotglob
shopt -s lastpipe

if mountpoint -q ${ESP_ROOT}; then
	echo "${ESP_ROOT} is already mounted, aborting..." 1>&2
	exit 1
fi

if ls ${ESP_ROOT}/* &> /dev/null; then
	echo "${ESP_ROOT} is not empty, aborting..." 1>&2
	exit 1
fi

DATA="$(efibootmgr -v)"
if [[ -z $DATA ]]; then
	echo "failed to read efi variables, aborting..." 1>&2
	exit 1
fi

echo "$DATA" | grep "^BootCurrent: " | read BOOT
if [[ -z $BOOT ]]; then
	echo "failed to determine current esp, aborting..." 1>&2
	exit 1
fi

echo "$DATA" | grep "^Boot${BOOT#BootCurrent: }" | grep --perl-regexp -io '[0-9a-f-]{36}' | read UUID
if [[ -z $UUID ]]; then
	echo "failed to find current esp's partition uuid, aborting..." 1>&2
	exit 1
fi

findmnt -n -l --source "PARTUUID=$UUID" --output "target" | grep -m 1 "^${ESP_ROOT}@[a-z]$" | read TRGT
if [[ -z $TRGT ]]; then
	echo "failed to find mountpoint of form ${ESP_ROOT}@[a-z] for current esp, aborting..." 1>&2
	exit 1
fi

mkdir -p ${ESP_ROOT}

chmod 0000 ${ESP_ROOT} &> /dev/null || true
chcon -u system_u -r object_r -t boot_t -l s0 ${ESP_ROOT} &> /dev/null || true

mount -o bind $TRGT ${ESP_ROOT}
exit $?
