#!/usr/bin/bash
# vim:set ts=3:

exec 1>&2

shopt -s dotglob
shopt -s lastpipe

if mountpoint -q "${ESP_ROOT}"; then
	echo "${ESP_ROOT} is already mounted, aborting..."
	exit 1
fi

if ls ${ESP_ROOT}/* &> /dev/null; then
	echo "${ESP_ROOT} is not empty, aborting..."
	exit 1
fi

TIME=0
TIMEOUT=10
EFIVARS='/sys/firmware/efi/efivars'
LDPUVAR='LoaderDevicePartUUID-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f'
while [[ $TIME -lt $TIMEOUT ]]; do
	if [[ -e $EFIVARS/$LDPUVAR ]]; then break; fi
	sleep 1
	TIME=$(($TIME+1))
done

# get the UUID of the ESP that sd-boot was loaded from when the system booted
# skip the first four bytes as they are not part of the UUID data
# translate uppercase to lowercase because findmnt matches case-sensitively
dd if="$EFIVARS/$LDPUVAR" bs=1 skip=4 conv=lcase status=none | tr -d \\000 \
	| read UUID

findmnt -n -l --source "PARTUUID=$UUID" --output "target" \
	| grep "^${ESP_ROOT}@[a-z]$" | read ESP_MOUNT
if [[ -z $ESP_MOUNT ]]; then
	echo "failed to find mountpoint of form ${ESP_ROOT}@[a-z]" \
		"for current esp, aborting..."
	exit 1
fi

mount -o bind "$ESP_MOUNT" "${ESP_ROOT}"
exit $?
